version: '2'
services:
  node_express:
    image: node
    container_name: smarthome
    hostname: smarthome
    volumes:
      - ".:/src"
    working_dir: /src
    command: [sh, -c, npm install && npm start]
    networks:
      - https_link
networks:
  https_link:
    external: true
